# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(762, 479)
        Form.setMinimumSize(QtCore.QSize(762, 479))
        Form.setMaximumSize(QtCore.QSize(762, 479))
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(180, 50, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(48)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Edit_username = QtWidgets.QLineEdit(Form)
        self.Edit_username.setGeometry(QtCore.QRect(250, 180, 211, 41))
        self.Edit_username.setObjectName("Edit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(Form)
        self.lineEdit_password.setGeometry(QtCore.QRect(250, 250, 211, 41))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.btn_login = QtWidgets.QPushButton(Form)
        self.btn_login.setGeometry(QtCore.QRect(290, 350, 111, 41))
        self.btn_login.setObjectName("btn_login")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(63, 41, 191, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/yangqing/.designer/Pic/picDemo.jpeg"))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "营养管理系统"))
        self.label_2.setText(_translate("Form", "营养管理系统"))
        self.Edit_username.setPlaceholderText(_translate("Form", "用户名"))
        self.lineEdit_password.setPlaceholderText(_translate("Form", "密码"))
        self.btn_login.setText(_translate("Form", "登录"))
